version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo-test
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: yourFavoriteUser
      MONGO_INITDB_ROOT_PASSWORD: ImCommingBTG
      MONGO_INITDB_URL: mongodb://yourFavoriteUser:ImCommingBTG@127.0.0.1:27017
